add_newline = true
command_timeout = 200
format = "$os[$directory$git_branch$git_status]($style)$character"

[os]
disabled = false
style = "bright-white"

[os.symbols]
Macos = "󰀵 "
Arch = "󰣇 "
Ubuntu = " "
Mint = "󰣭 "
Linux = " "

[character]
error_symbol = "[✘](bold red)"
success_symbol = "[❯](bold bright-white)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
fish_style_pwd_dir_length = 2
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bright-green"

[git_status]
format = '$all_status$ahead_behind'
ahead = "[⇡${count}](green) "
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](bright-yellow) "
behind = "[⇣${count}](bright-yellow) "
conflicted = "[](red) "
up_to_date = ""
untracked = "[?](bright-yellow) "
modified = "[](bright-yellow) "
stashed = ""
staged = ""
renamed = ""
deleted = ""
